---
- name: Install OpenJDK 17
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
  become: yes

- name: Verify Java installation
  ansible.builtin.command: java -version
  register: java_version
  changed_when: false
  become: yes

- name: Show installed Java version
  ansible.builtin.debug:
    msg: "{{ java_version.stderr }}"
