name: Terraform Validate

on:
  push:
    branches:
      - main
      - dev
      - feature/*
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Fmt Check
        run: terraform fmt -check -recursive terraform/

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init -backend=false -input=false

      - name: Terraform Validate
        working-directory: terraform/environments/dev
        run: terraform validate
